app:
  port: 8080
  shutdown:
    gracePeriod: 0
    stopTimeout: 0
    timeUnit: "SECONDS"

http:
  connectTimeoutMs: 1000
  connectionRequestTimeoutMs: 1000
  maxConnTotal: 100
  maxConnPerRoute: 100

adyen:
  url: "https://checkout-test.adyen.com"
  apiKey: ${ADYEN_API_KEY}
  apiVersion: "v70"
  merchantAccount: ${ADYEN_MERCHANT_ACCOUNT}